<?php
/**
 * Responsive image: WebP variants (srcset, generated by the Media helper) with the original as fallback,
 * explicit width/height (no layout shift), lazy loading below the fold, fetchpriority for the LCP image.
 * Parameters: Components::SPECS['picture'].
 *
 * width/height describe the box for the image as designed. When the actual file has another shape (a logo
 * replaced in Appearance), the height is kept and the width follows the file, and the variant widths and the
 * sizes hint scale with it, so the browser reserves the right space and still picks a sharp variant.
 *
 * @var \Gate\Core\View $view
 * @var array{src: string, alt: string, width: int, height: int, widths: list<int>, sizes: ?string, loading: string, priority: bool, class: string} $p
 */

$media = $view->shared('media');
$webp = '';
$width = $p['width'];
$height = $p['height'];
$widths = array_values(array_filter($p['widths'], 'is_int'));
$sizes = $p['sizes'];
if ($media instanceof \Gate\Site\Media) {
    $info = $media->size($p['src']);
    if ($info !== null && $width > 0 && $height > 0) {
        $factor = ($info[0] / $info[1]) / ($width / $height);
        if (abs($factor - 1) > 0.02) {
            $width = max(1, (int) round($height * $info[0] / $info[1]));
            $widths = array_map(static fn (int $w): int => max(16, (int) round($w * $factor)), $widths);
            $sizes = $sizes === null ? null : (string) preg_replace_callback('/(\d+)px/', static fn (array $m): string => (int) round((int) $m[1] * $factor) . 'px', $sizes);
        }
    }
    if ($widths !== []) {
        $webp = $media->picture($p['src'], $widths)['webp'];
    }
}
$img = '<img' . ($p['class'] !== '' ? ' class="' . e_attr($p['class']) . '"' : '') . ' src="' . e_url($p['src']) . '" alt="' . e_attr($p['alt']) . '" width="' . $width . '" height="' . $height . '"'
    . ($p['loading'] === 'lazy' ? ' loading="lazy"' : '') . ' decoding="async"' . ($p['priority'] ? ' fetchpriority="high"' : '') . '>';
?>
<?php if ($webp !== ''): ?>
<picture><source type="image/webp" srcset="<?= e_attr($webp) ?>"<?= $sizes !== null ? ' sizes="' . e_attr($sizes) . '"' : '' ?>><?= $img ?></picture>
<?php else: ?>
<?= $img ?>
<?php endif; ?>
