<?php
/**
 * @var \Gate\Core\View $view
 * @var string $qrSvg generated by bacon/bacon-qr-code
 * @var list<string> $secretGroups
 * @var string|null $error
 * @var string $adminPath
 */
?>
<div class="flex gap-20 agrow">
  <div class="acard agrow panel-fields">
    <div class="card-intro card-intro--flush">
      <h2 class="h3"><?= e($view->t('admin.two_factor.setup_step1')) ?></h2>
      <span class="muted"><?= e($view->t('admin.two_factor.setup_step1_desc')) ?></span>
    </div>
    <div class="qr" role="img" aria-label="<?= e_attr($view->t('admin.two_factor.qr_label')) ?>"><?= $qrSvg /* SVG markup generated server-side from the otpauth URI; contains no user input beyond the escaped email */ ?></div>
    <div class="card-intro card-intro--flush">
      <span class="muted"><?= e($view->t('admin.two_factor.manual_key')) ?></span>
      <span class="secret-key"><?php foreach ($secretGroups as $group): ?><?= $view->component('status-pill', ['label' => $group]) ?><?php endforeach; ?></span>
    </div>
  </div>
  <div class="side-400">
    <form class="acard panel-fields" method="post" action="<?= e_url($adminPath . '/security/two-factor/confirm') ?>" novalidate>
      <?= $view->csrfField() ?>
      <div class="card-intro card-intro--flush">
        <h2 class="h3"><?= e($view->t('admin.two_factor.setup_step2')) ?></h2>
        <span class="muted"><?= e($view->t('admin.two_factor.setup_step2_desc')) ?></span>
      </div>
<?php if ($error !== null): ?>
      <?= $view->component('notice', ['title' => $error, 'role' => 'alert']) ?>

<?php endif; ?>
      <?= $view->component('input', ['name' => 'code', 'label' => $view->t('admin.two_factor.code_6'), 'autocomplete' => 'one-time-code', 'inputmode' => 'numeric', 'required' => true, 'autofocus' => true]) ?>
      <div class="actions"><?= $view->component('button', ['label' => $view->t('admin.actions.cancel'), 'variant' => 'admin-secondary', 'href' => $adminPath . '/security']) ?><?= $view->component('button', ['label' => $view->t('admin.two_factor.activate'), 'variant' => 'admin-primary', 'type' => 'submit', 'icon' => 'fa-solid fa-check', 'iconPosition' => 'start']) ?></div>
    </form>
  </div>
</div>
