#!/usr/bin/env python3
"""Builds the admin panel's Font Awesome subset.

Scans the PHP sources, config and admin scripts for the icons in use ("fa-solid fa-envelope"), subsets the Font Awesome
Free fonts to exactly those glyphs and writes public/assets/css/icons.css (the @font-face rules and one
`.fa-name{--fa:"\\f0e0"}` rule per icon). The base rules (.fa-solid, .fa-regular, :before) live in admin.css.

Usage: python3 tools/icons/build.py /path/to/fontawesome-free/package   (npm: @fortawesome/fontawesome-free 6.x)
Needs fonttools and brotli (pip install fonttools brotli).
"""
import hashlib
import os
import re
import sys

import yaml
from fontTools import subset

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SCAN = ['app', 'config', 'public/assets/js/admin-gate.js']
FONTS = {'solid': ('fa-solid-900', 900, 'Font Awesome 6 Free'), 'regular': ('fa-regular-400', 400, 'Font Awesome 6 Free'),
         'brands': ('fa-brands-400', 400, 'Font Awesome 6 Brands')}
# Icons whose name is built in code (the toasts of app.js: 'fa-solid ' + name), not found by the scan.
EXTRA = [('solid', 'check'), ('solid', 'xmark'), ('solid', 'info'), ('solid', 'exclamation')]
PAIR = re.compile(r'fa-(solid|regular|brands) fa-([a-z0-9-]+)')


def used_icons():
    found = set(EXTRA)
    for entry in SCAN:
        path = os.path.join(ROOT, entry)
        if not os.path.exists(path):
            continue
        files = [path] if os.path.isfile(path) else [os.path.join(d, f) for d, _, fs in os.walk(path) for f in fs if f.endswith('.php')]
        for file in files:
            with open(file, encoding='utf-8') as fh:
                found.update(PAIR.findall(fh.read()))
    return sorted(found)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    package = sys.argv[1]
    with open(os.path.join(package, 'metadata', 'icons.yml'), encoding='utf-8') as fh:
        meta = yaml.safe_load(fh)
    icons = used_icons()
    per_style = {style: set() for style in FONTS}
    rules = {}
    for style, name in icons:
        info = meta.get(name)
        if info is None or style not in info['styles']:
            sys.exit(f'fa-{style} fa-{name}: not in Font Awesome Free')
        per_style[style].add(int(info['unicode'], 16))
        rules[name] = info['unicode']
    css = ['/* Font Awesome Free subset (fonts: SIL OFL 1.1, CSS: MIT; see ../webfonts/FONTAWESOME-LICENSE.txt).',
           '   Generated by tools/icons/build.py: do not edit by hand. */']
    for style, (file, weight, family) in FONTS.items():
        if not per_style[style]:
            continue
        target = os.path.join(ROOT, 'public', 'assets', 'webfonts', file + '.woff2')
        options = subset.Options()
        options.flavor = 'woff2'
        options.layout_features = []
        options.name_IDs = ['*']
        font = subset.load_font(os.path.join(package, 'webfonts', file + '.ttf'), options)
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=sorted(per_style[style]))
        subsetter.subset(font)
        subset.save_font(font, target, options)
        with open(target, 'rb') as fh:
            version = hashlib.md5(fh.read()).hexdigest()[:10]
        css.append(f'@font-face{{font-family:"{family}";font-style:normal;font-weight:{weight};font-display:block;'
                   f'src:url(../webfonts/{file}.woff2?v={version}) format("woff2")}}')
    for name in sorted(rules):
        css.append(f'.fa-{name}{{--fa:"\\{rules[name]}"}}')
    with open(os.path.join(ROOT, 'public', 'assets', 'css', 'icons.css'), 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(css) + '\n')
    print(f'{len(rules)} icons: ' + ', '.join(f'{s}/{n}' for s, n in icons))


if __name__ == '__main__':
    main()
