<?php

declare(strict_types=1);

/*
 * Default configuration. Do not put secrets here.
 * The installer writes config/config.local.php (database credentials, app key, URL), which overrides these values.
 * This directory must not be web-accessible: the web root is /public.
 */
return [
    'app' => [
        'name' => 'GATE Lebanon',
        // production | local. "local" only relaxes the Secure cookie flag on plain-HTTP development servers.
        'env' => 'production',
        'debug' => false,
        // Absolute base URL without trailing slash, e.g. https://gatelebanon.org
        'url' => '',
        // base64-encoded 32 random bytes; generated by the installer. Used for encryption at rest and HMACs.
        'key' => '',
        'timezone' => 'Europe/Brussels',
    ],
    'db' => [
        'host' => '127.0.0.1',
        'port' => 3306,
        'name' => '',
        'user' => '',
        'pass' => '',
        'charset' => 'utf8mb4',
    ],
    // IPs of reverse proxies whose X-Forwarded-For / X-Forwarded-Proto headers may be trusted (e.g. a CDN).
    'trusted_proxies' => [],
    'session' => [
        'name' => 'gate_session',
    ],
    // Operations (see MAINTENANCE.md). Override in config.local.php; credentials belong there, never here.
    'ops' => [
        // Developer address for error reports: at most one email per hour, never one per error. Empty = off.
        'error_email' => '',
        // Days of storage/logs/app-*.log to keep.
        'log_retention_days' => 30,
        'backup' => [
            // Where `bin/console backup:run` writes. Empty = storage/backups. Never inside the web root.
            'dir' => '',
            'retention_days' => 30,
            // Optional second copy: a folder (e.g. a synced drive) or ftp://user:pass@host/path, ftps://…, sftp://…
            'offsite' => '',
        ],
    ],
];
