#!/usr/bin/env python3
"""
Builds app/Views/site/parts/map-paths.php: SVG paths of Lebanon's governorates for the "Where we work" map.

Source: geoBoundaries LBN ADM1 (simplified), CC BY 4.0, https://www.geoboundaries.org
(tools/map/geoBoundaries-LBN-ADM1_simplified.geojson). Run from the repository root:

    python3 tools/map/build.py
"""
import json
import math
import os

SRC = os.path.join(os.path.dirname(__file__), 'geoBoundaries-LBN-ADM1_simplified.geojson')
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'app', 'Views', 'site', 'parts', 'map-paths.php')

# geoBoundaries shape names -> region keys (Gate\Content\EntryTypes::REGIONS)
KEYS = {
    'Aakkâr': 'akkar', 'Liban-Nord': 'north', 'Baalbek-Hermel': 'baalbek-hermel', 'Béqaa': 'bekaa',
    'Keserwan-Jbeil': 'keserwan-jbeil', 'Mont-Liban': 'mount-lebanon', 'Beyrouth': 'beirut',
    'Liban-Sud': 'south', 'Nabatîyé': 'nabatieh',
}
WIDTH = 360.0
TOLERANCE = 0.6  # pixels, Douglas-Peucker


def rings(geometry):
    polys = geometry['coordinates'] if geometry['type'] == 'MultiPolygon' else [geometry['coordinates']]
    for poly in polys:
        for ring in poly:
            yield ring


def simplify(points, tol):
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dmax, index = 0.0, 0
    for i in range(1, len(points) - 1):
        x0, y0 = points[i]
        dx, dy = x2 - x1, y2 - y1
        d = abs(dy * x0 - dx * y0 + x2 * y1 - y2 * x1) / (math.hypot(dx, dy) or 1)
        if d > dmax:
            dmax, index = d, i
    if dmax > tol:
        return simplify(points[:index + 1], tol)[:-1] + simplify(points[index:], tol)
    return [points[0], points[-1]]


def main():
    data = json.load(open(SRC, encoding='utf-8'))
    all_pts = [pt for f in data['features'] for ring in rings(f['geometry']) for pt in ring]
    min_lon = min(p[0] for p in all_pts); max_lon = max(p[0] for p in all_pts)
    min_lat = min(p[1] for p in all_pts); max_lat = max(p[1] for p in all_pts)
    k = math.cos(math.radians((min_lat + max_lat) / 2))
    scale = WIDTH / ((max_lon - min_lon) * k)
    height = (max_lat - min_lat) * scale

    def project(p):
        return ((p[0] - min_lon) * k * scale, (max_lat - p[1]) * scale)

    paths = {}
    centers = {}
    for f in data['features']:
        key = KEYS[f['properties']['shapeName']]
        d = []
        xs, ys, n = 0.0, 0.0, 0
        for ring in rings(f['geometry']):
            raw = [project(p) for p in ring]
            pts = simplify(raw, TOLERANCE)
            if len(pts) < 4:
                # Small shapes (Beirut) keep their full outline.
                pts = raw
            if len(pts) < 3:
                continue
            d.append('M' + 'L'.join('%.1f,%.1f' % p for p in pts) + 'Z')
            for x, y in pts:
                xs += x; ys += y; n += 1
        paths[key] = ''.join(d)
        centers[key] = (round(xs / n, 1), round(ys / n, 1))

    with open(OUT, 'w', encoding='utf-8') as out:
        out.write('<?php\n\n/*\n * Generated by tools/map/build.py — do not edit by hand.\n'
                  ' * Governorates of Lebanon from geoBoundaries (CC BY 4.0, https://www.geoboundaries.org).\n */\n\n')
        out.write('return [\n    \'viewBox\' => \'0 0 %d %d\',\n    \'regions\' => [\n' % (round(WIDTH), round(height)))
        for key in KEYS.values():
            out.write("        '%s' => ['d' => '%s', 'x' => %s, 'y' => %s],\n" % (key, paths[key], centers[key][0], centers[key][1]))
        out.write('    ],\n];\n')
    print('wrote', OUT, os.path.getsize(OUT), 'bytes')


if __name__ == '__main__':
    main()
